image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - .imageio/ffmpeg/*

before_script:
  - python3 -V
  - pip3 install virtualenv
  - virtualenv ../venv
  - source ../venv/bin/activate
  - pip3 install -r requirements.txt

stages:
  - pep8
  - unittest
 
pep8:
  stage: pep8
  script: "pycodestyle web --max-line-length=120 --ignore=E402 --show-source --show-pep8"

unittest:
  stage: unittest
  script:
  - nose2 web -C
 