image: python:3.6-stretch

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  SECRET_KEY: "SuperSecret"
  DATABASE_URL: "sqlite:////tmp/db.sqlite"

cache:
  paths:
    - .cache/pip
    - .imageio/ffmpeg/*

before_script:
  - python3 -V
  - pip3 install -r requirements.txt

stages:
  - code-test

code-test:
  stage: code-test
  script:
  - nose2 web -C
  - pycodestyle web --max-line-length=120 --ignore=E402 --show-source --show-pep8
