image: python:3.6-stretch

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  SECRET_KEY: "SuperSecret"
  DATABASE_URL: "sqlite:////tmp/db.sqlite"
  GOOGLE_API_KEY: "GOOGLE_API_KEY"

cache:
  paths:
    - .cache/pip
    - .imageio/ffmpeg/*

before_script:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - apt-get update && apt-get install nodejs yarn 
  - python3 -V
  - pip3 install -r requirements.txt
  - yarn
  - yarn build

stages:
  - code-test

code-test:
  stage: code-test
  script:
  - nose2 web -C
  - pycodestyle web --max-line-length=120 --ignore=E402 --show-source --show-pep8
